import = [
   "~/.config/alacritty/themes/carbonfox.toml"
]

[shell]
program = "/bin/zsh"

[env]
TERM = "screen-256color"
LC_CTYPE = "en_US.UTF-8"
LANG = "en_US.UTF-8"
LANGUAGE = "en_US.UTF-8"

[font.normal]
family = "Hack Nerd Font Mono"
style = "regular"

[font.bold]
family = "Hack Nerd Font Mono"
style = "bold"

[font.italic]
family = "Hack Nerd Font Mono"
style = "italic"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "bold italic"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
   { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" }
]
