import = [
    "~/.config/alacritty/themes/themes/nightfox.toml"
]

[shell]
program = "/bin/zsh"

[font.normal]
family = "Hack Nerd Font Mono"
style = "regular"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
